# Generated by Django 5.2.7 on 2025-11-08 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('carga_horaria', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('semestre', models.CharField(max_length=6)),
                ('curso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sistema.usuario')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('data_de_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sistema.usuario')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_de_contratacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sistema.usuario')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_de_contratacao', models.DateField()),
                ('titulacao', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_entrega', models.DateTimeField(auto_now_add=True)),
                ('id_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.atividade')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.aluno')),
            ],
            options={
                'verbose_name': 'Entrega de Atividade',
                'verbose_name_plural': 'Entregas de Atividades',
                'unique_together': {('id_aluno', 'id_atividade')},
            },
        ),
        migrations.CreateModel(
            name='ProfessorDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.disciplina')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.professor')),
            ],
            options={
                'verbose_name': 'Associação Professor-Disciplina',
                'verbose_name_plural': 'Associações Professor-Disciplina',
                'unique_together': {('id_professor', 'id_disciplina')},
            },
        ),
        migrations.CreateModel(
            name='TurmaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.disciplina')),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.turma')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.professor')),
            ],
            options={
                'verbose_name': 'Módulo de Turma/Disciplina',
                'verbose_name_plural': 'Módulos de Turmas/Disciplinas',
                'unique_together': {('id_turma', 'id_disciplina')},
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('conteudo', models.TextField()),
                ('id_turma_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.turmadisciplina')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='id_turma_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.turmadisciplina'),
        ),
        migrations.DeleteModel(
            name='entrada',
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(related_name='turmas', to='sistema.aluno'),
        ),
        migrations.AddField(
            model_name='turma',
            name='id_coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.coordenador'),
        ),
    ]
