# Generated by Django 5.2.7 on 2025-11-08 15:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_usuario_atividade_disciplina_turma_aluno_coordenador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_aluno', serialize=False, to='sistema.usuario'),
        ),
        migrations.AlterField(
            model_name='alunoatividade',
            name='id_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_entregues', to='sistema.aluno'),
        ),
        migrations.AlterField(
            model_name='alunoatividade',
            name='id_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='sistema.atividade'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='id_turma_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='sistema.turmadisciplina'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='id_turma_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='sistema.turmadisciplina'),
        ),
        migrations.AlterField(
            model_name='professordisciplina',
            name='id_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='sistema.disciplina'),
        ),
        migrations.AlterField(
            model_name='professordisciplina',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas_ministradas', to='sistema.professor'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='id_coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='sistema.coordenador'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='semestre',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Semestre deve estar no formato YYYY.1 ou YYYY.2', regex='^[0-9]{4}\\.[12]$')]),
        ),
        migrations.AlterField(
            model_name='turmadisciplina',
            name='id_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_associadas', to='sistema.disciplina'),
        ),
        migrations.AlterField(
            model_name='turmadisciplina',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_ministrados', to='sistema.professor'),
        ),
        migrations.AlterField(
            model_name='turmadisciplina',
            name='id_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='sistema.turma'),
        ),
    ]
