# Generated by Django 5.2.7 on 2025-11-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_alter_aluno_usuario_alter_coordenador_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunoatividade',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='entregas/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='alunoatividade',
            name='resposta_texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
