# Generated by Django 5.2.7 on 2025-11-12 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_alunoatividade_arquivo_alunoatividade_resposta_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_prova1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota_prova2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=15)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='sistema.aluno')),
                ('id_turma_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_modulo', to='sistema.turmadisciplina')),
            ],
            options={
                'verbose_name': 'Aluno no Módulo',
                'verbose_name_plural': 'Alunos no Módulo',
                'unique_together': {('id_aluno', 'id_turma_disciplina')},
            },
        ),
    ]
